In [10]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import scipy

In [11]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [[0, 1], [0, 6], [0, 7], 
         [1, 2], [1, 7], 
         [2, 1], [2, 7], 
         [3, 5], [3, 7], 
         [4, 5], 
         [5, 6], 
         [6, 5], 
         [7, 6],]

G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

print(G)

incidence_matrix = -nx.incidence_matrix(G, oriented=True)

print(incidence_matrix.toarray())

E = np.array(incidence_matrix.toarray())


[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  1. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1. -1.]
 [ 0.  0. -1.  0. -1.  0. -1.  0. -1.  0.  0.  0.  1.]]


In [22]:
a1 = np.where(E.T == 1)
a2 = np.where(E.T == -1)

G2 = nx.DiGraph()

for i in range(len(E)):
    G2.add_node(i)

for i in range(len(a1[1])):
    foo = a1[1][i]
    bar = a2[1][i]
    G2.add_edge(foo, bar)

am = nx.adjacency_matrix(G2)

A = np.array(am.toarray())



In [23]:
G3 = nx.DiGraph(A)

incidence_matrix2 = -nx.incidence_matrix(G3, oriented=True)

print(incidence_matrix2.toarray())

E2 = np.array(incidence_matrix2.toarray())



[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  1. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1. -1.]
 [ 0.  0. -1.  0. -1.  0. -1.  0. -1.  0.  0.  0.  1.]]
[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  1. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1. -1.]
 [ 0.  0. -1.  0. -1.  0. -1.  0. -1.  0.  0.  0.  1.]]
